-- Strict cleanup: drop every index reported as unused_index by Supabase linter.
-- Generated on 2026-02-27.

DO $do$
DECLARE
  idx_name TEXT;
BEGIN
  FOREACH idx_name IN ARRAY ARRAY[
    'idx_owner_entities_account',
    'idx_property_owners_account',
    'idx_expenses_account_id',
    'idx_user_oauth_tokens_account_id',
    'idx_user_oauth_tokens_user_id',
    'idx_properties_manager_user_id',
    'idx_tenant_invites_unit_id',
    'idx_vendor_invites_account_id',
    'idx_tenant_payment_methods_account_id',
    'idx_vendor_profiles_is_active',
    'idx_vendor_services_vendor_profile_id',
    'idx_maintenance_requests_unit_id',
    'idx_maintenance_requests_property_id',
    'idx_maintenance_requests_created_by',
    'idx_maintenance_requests_created_at',
    'idx_maintenance_assignments_account_id',
    'idx_maintenance_assignments_request_id',
    'idx_maintenance_assignments_vendor_id',
    'idx_maintenance_assignments_status',
    'idx_payments_lease_id',
    'idx_expenses_property_id',
    'idx_expenses_category_id',
    'idx_expenses_expense_date',
    'idx_messages_thread_id',
    'idx_messages_created_at',
    'idx_notifications_account_id',
    'idx_notifications_is_read',
    'idx_notifications_created_at',
    'idx_showings_property_id',
    'idx_showings_unit_id',
    'idx_rental_applications_property_id',
    'idx_rental_applications_status',
    'idx_hvac_filter_subs_account_id',
    'idx_hvac_filter_subs_unit_id',
    'idx_unit_hvac_status_account',
    'idx_unit_hvac_status_unit',
    'idx_analytics_events_account_id',
    'idx_analytics_events_created_at',
    'idx_audit_log_account_id',
    'idx_audit_log_entity',
    'idx_audit_log_created_at',
    'idx_user_profiles_email',
    'idx_owners_account',
    'idx_tenants_account',
    'idx_vendors_account',
    'idx_vendors_properties_account',
    'idx_maintenance_comments_account',
    'idx_maintenance_attachments_account',
    'idx_subscriptions_account',
    'idx_invoices_account',
    'idx_activity_events_user',
    'idx_hvac_batches_account',
    'idx_hvac_enrollments_account',
    'idx_hvac_enrollments_unit',
    'idx_hvac_delivery_schedules_account',
    'idx_hvac_delivery_schedules_enrollment',
    'idx_screening_results_account',
    'idx_screening_results_application',
    'idx_message_templates_category',
    'idx_reminder_schedules_reminder',
    'idx_reminder_schedules_scheduled',
    'idx_reminder_runs_reminder',
    'idx_reminder_logs_reminder',
    'idx_expenses_property',
    'idx_conversations_participants',
    'idx_outbound_messages_reminder',
    'idx_outbound_messages_conversation',
    'idx_outbound_messages_message',
    'idx_conversation_satisfaction_conversation',
    'idx_gmail_message_links_account',
    'idx_gmail_message_links_message',
    'idx_expenses_date',
    'idx_expenses_category'
  ]
  LOOP
    EXECUTE format('DROP INDEX IF EXISTS public.%I;', idx_name);
  END LOOP;
END
$do$;
